### ISSUE TITLE
Fresh install renders 'no matches for kind "Application"'

### ISSUE THREAD

**Issue by pdmack** [kubeflow/kubeflow#1933]
I've seen this twice but it seems to remedy itself by regenerating and reapplying the ks app.

/cc @kkasravi 

```
+ ks apply default -c application
INFO Applying customresourcedefinitions applications.app.k8s.io
INFO Creating non-existent customresourcedefinitions applications.app.k8s.io
ERROR handle object: patching object from cluster: merging object with existing state: unable to recognize "/tmp/ksonnet-mergepatch884886323": no matches for kind "Application" in version "app.k8s.io/v1beta1"
```

**Comment by pdmack** [comment]
Yes

**Comment by jlewi** [comment]
@kkasravi @pdmack any idea whether this is still happening?

**Comment by cheyang** [comment]
I'm able to reproduce it in brachn `v0.4-branch`. Are there any workarounds?

```
${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s
+ ks apply default -c application
INFO Updating customresourcedefinitions applications.app.k8s.io
INFO  Creating non-existent customresourcedefinitions applications.app.k8s.io
ERROR handle object: merging object with existing state: unable to recognize "/tmp/ksonnet-mergepatch060322179": no matches for kind "Application" in version "app.k8s.io/v1beta1"
```

**Comment by xuchenCN** [comment]
Hi @cheyang  I encountered the same issue , but its disppear when I re-apply the ksonnet ,  have some idea for that ?

**Comment by kkasravi** [comment]
you should try 
```
      ks show default -c metacontroller -c application > default.yaml
      kubectl apply --validate=false -f default.yaml
```

**Comment by cheyang** [comment]
> Hi @cheyang I encountered the same issue , but its disppear when I re-apply the ksonnet , have some idea for that ?
> BTW , may I ask what do you do to overcome the GFW to pull the gcr.io images ?

You can run this on Alibaba Cloud by following the document below which is in Chinese: https://yq.aliyun.com/articles/686672

**Comment by 13567436138** [comment]
when i apply  ks show default -c metacontroller -c application > default.yaml
I got  ks show default -c metacontroller -c application > default.yaml
what‘s going on？

**Comment by 13567436138** [comment]
got  ERROR finding app root from starting path: : unable to find ksonnet project

**Comment by jlewi** [comment]
I observed this error. The logs clearly indicate the apps resource CR was created.

```
customresourcedefinition.apiextensions.k8s.io "applications.app.k8s.io" created
...
INFO|2019-03-02T17:57:06|/mnt/test-data-volume/auto_deploy/testing/py/kubeflow/testing/util.py|71| unable to recognize "default.yaml": no matches for kind "Application" in version "app.k8s.io/v1beta1"
```
[pods.txt](https://github.com/kubeflow/kubeflow/files/2922394/pods.txt)

I wonder if it takes some time for the CRD to be loaded. Does simply retrying help?

**Comment by jlewi** [comment]
It looks like retrying fixes things. 

Below are the logs the first time `kubectl apply --validate=false -f default.yaml` it fails with the error about the application kind even though the custom resource was created. Rerunning the `kubectl apply --validate=false -f default.yaml` it succeeds.

[logs.txt](https://github.com/kubeflow/kubeflow/files/2922411/logs.txt)

**Comment by andrewcheny** [comment]
I have exactly the same error on the first run (fresh install). I run the script for the 2nd time and the problem is fixed.

**Comment by jlewi** [comment]
I wonder if there is a race condition and we are trying to create an App resource before the App CRD is fully ready?

**Comment by kkasravi** [comment]
since we removed the application component (in lieu of the kubernetes-sigs/application controller) I don't think this can occur anymore. Closing.

**Comment by jonasdebeukelaer** [comment]
Hey reopening to say this error still popped up for me on a 1.1 install, but at a different point:
```
service/application-controller-service created
serviceaccount/application-controller-service-account created
error: unable to recognize ".build/application/app.k8s.io_v1beta1_application_application-controller-kubeflow.yaml": no matches for kind "Application" in version "app.k8s.io/v1beta1"
make: *** [apply-kubeflow] Error 1
```

rerunning `make apply` does fix it as before.

also getting it for kind `Image`:
```
service/controller created
service/webhook created
serviceaccount/controller created
error: unable to recognize ".build/knative/caching.internal.knative.dev_v1alpha1_image_queue-proxy.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
make: *** [apply-kubeflow] Error 1
```

and `Profile`:
```
serviceaccount/pytorch-operator created
serviceaccount/tf-job-dashboard created
serviceaccount/tf-job-operator created
error: unable to recognize ".build/kubeflow-apps/kubeflow.org_v1beta1_profile_default-profile.yaml": no matches for kind "Profile" in version "kubeflow.org/v1beta1"
make: *** [apply-kubeflow] Error 1
```

and here too rerunning the command works.

**Comment by rystadedgaras** [comment]
I have the same error when deploying on AKS. To deploy I'm using this command:

export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_k8s_istio.v1.2.0.yaml"
kfctl apply -V -f ${CONFIG_URI}

I am getting this error:
`WARN[0077] Encountered error applying application application:  (kubeflow.error): Code 500 with message: Apply.Run : [unable to recognize "/tmp/kout234490513": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1", unable to recognize "/tmp/kout234490513": no matches for kind "Application" in version "app.k8s.io/v1beta1"]  filename="kustomize/kustomize.go:284"`

I've tried rerunning, but the same errors keeps popping up.

**Comment by Juandavi1** [comment]
same here

**Comment by obeyda** [comment]
having the same issue on AKS with kfctl_k8s_istio.v1.2.0.yaml
