### ISSUE TITLE
kfctl delete leaves behind istio resources

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/kubeflow#3767]
When deleting a Kubeflow deployment using kfctl delete, it deletes 'kubeflow' namespace but leaves behind the istio-system namespace. Therefore the istio resources still hang around after deleting Kubeflow deployment.

I can manaully delete the istio-system namespace, but ideally kfctl delete can do the complete cleanup.

**Comment by Jeffwan** [comment]
I also see this and just wondering it's a by design feature or a bug. Last time I remember someone mentioned there's concern to delete existing istio people deployed?

**Comment by blublinsky** [comment]
Istio namespace seems to clean up correctly, but CRDs:
experiments.kubeflow.org
notebooks.kubeflow.org
poddefaults.kubeflow.org
profiles.kubeflow.org
pytorchjobs.kubeflow.org
scheduledworkflows.kubeflow.org
tfjobs.kubeflow.org
trials.kubeflow.org
viewers.kubeflow.org
workflows.argoproj.io
Are left behind

**Comment by blublinsky** [comment]
Also I see cluster roles (which are global) not being deleted either

**Comment by jlewi** [comment]
@kkasravi @yanniszark Thoughts on what the desired behavior should be?

@kkasravi Is not deleting the CRDs WAI or is that a bug?

**Comment by johnugeorge** [comment]
Deleting namespace 'kubeflow' alone doesn't seem right. All global resources and non-kubeflow resources are left behind.  This is a bigger problem when we try KF installation on existing k8s clusters(using` kfctl_k8s_istio.yaml`). The expectation of` Kfctl delete` would be restoring the state back to where we were(without Kubeflow).  Why don't we delete the same way as we created each component, instead of namespace delete?.   With partial deletes, it will be difficult to debug and will  lead to many unexpected errors. 

Related: https://github.com/kubeflow/kubeflow/issues/3684 

Also, Can we get the fix this in 0.6 itself?

**Comment by blublinsky** [comment]
Fully agreed. All CRDs, Cluster Roles and Role binding should be cleaned up

**Comment by kkasravi** [comment]
storage is also not removed #3646 

This is a fairly recent regression. Earlier behavior prior to the regression was to delete the namespace and then delete all cluster level resources by label.

Probably the better approach is to have the client (kfctl) just delete the applications and have the application-controller delete the resources since it has set each resource's owner to itself. This would include cluster-level resources. We definitely need an e2e test to verify this behavior.

**Comment by kkasravi** [comment]
@kunmingg @zabbasi @jlewi @lluunn @gabrielwen 

One question related to `kfctl delete all` is what is done with profiles. Are these deleted? Since an individual's profile may also include cloud-provider related resources, are these deleted as well?
See my comment above about having the application-controller do cleanup.

**Comment by holdenk** [comment]
I ran into this on master ( df2b68d92cf15374b1706d3d91b8123972b8920c ), and the `istio-system` namespace was still there.

**Comment by holdenk** [comment]
It also left behind the default namespace (for me that was `kubeflow-programmerboo`).

**Comment by abhi-g** [comment]
I had a discussion with @jlewi @lluunn about this. It seems like istio-system is the namespace created by the istio deployment. If a deployment of Kubeflow was done into a system that already has istio configured, it will have an istio-system namespace. In this case if the kfctl delete removes the istio-namespace it will end up deleting all pre-existing policies. 

I don't know what the correct solution is:
 1. Create kubeflow specific istio mesh in a different namespace: This seems complex and I am not sure if it will work correctly. FYI getting Istio configured and working was non-trivial..
or 2. Delete all the kubeflow specific istio policies that were added during deployment. this could get trickly as well and we'll always need to remember to update deletion symmetric to any policy changes.

**Comment by holdenk** [comment]
So from trying to deploy k8s with istio, right now if istio is already deployed it fails to deploy, so I think worrying about stomping on an existing istio namespace is perhaps not an immediate concern.

**Comment by johnugeorge** [comment]
If user has opted to install istio through k8s, it should be deleted as well. If he has opted not to install istio, he would have commented out already https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_k8s_istio.yaml#L19  Can't we use the same config as the source of truth to decide what components to delete?

**Comment by kkasravi** [comment]
In the past we've used labels, so I think there may have been a regression. 
I'll try and get some cycles to fix by Monday. Assigning myself to this...

**Comment by discordianfish** [comment]
https://github.com/kubeflow/kubeflow/issues/2415 is about cleaning up all resources but was closed. Not sure if fixed and this is a regression or not. These are the resources that are left behind after running `kfctl delete`:
```
$ kubectl api-resources --verbs=list -o name  | grep -v '^componentstatuses$'| xargs -n 1 kubectl get --all-namespaces --show-kind --ignore-not-found -l app.kubernetes.io/part-of=kubeflow
NAME                                                                                        CREATED AT
customresourcedefinition.apiextensions.k8s.io/notebooks.kubeflow.org                        2019-08-29T16:50:52Z
customresourcedefinition.apiextensions.k8s.io/seldondeployments.machinelearning.seldon.io   2019-08-29T12:09:35Z
customresourcedefinition.apiextensions.k8s.io/tfjobs.kubeflow.org                           2019-08-29T16:52:05Z
NAME                                                                                AGE
clusterrolebinding.rbac.authorization.k8s.io/jupyter-web-app-cluster-role-binding   3d17h
clusterrolebinding.rbac.authorization.k8s.io/notebook-controller-role-binding       3d17h
clusterrolebinding.rbac.authorization.k8s.io/seldon-operator-manager-rolebinding    3d17h
clusterrolebinding.rbac.authorization.k8s.io/tf-job-dashboard                       3d17h
clusterrolebinding.rbac.authorization.k8s.io/tf-job-operator                        3d17h
NAME                                                                 AGE
clusterrole.rbac.authorization.k8s.io/jupyter-web-app-cluster-role   80m
clusterrole.rbac.authorization.k8s.io/notebook-controller-role       3d17h
clusterrole.rbac.authorization.k8s.io/seldon-operator-manager-role   3d17h
clusterrole.rbac.authorization.k8s.io/tf-job-dashboard               77m
clusterrole.rbac.authorization.k8s.io/tf-job-operator                77m
```

(For some reason get componentstatuses returns all statuses, no matter what label selector is used. So I've excepted it here)

**Comment by discordianfish** [comment]
Btw, while this might seem like a 'nice to have', it's actually crucial to have a clean way to remove the resources since otherwise it's impossible to ever update/upgrade kubeflow given that right now it means re-installing from a clean slate. I've ran into a multitude of problems because of resources that weren't deleted and hard to find 'manually'. So I hope we can get a fix for this soon.

**Comment by discordianfish** [comment]
Looks like there are more resources not labeled with `app.kubernetes.io/part-of=kubeflow`:
```
$ kubectl api-resources --verbs=list -o name  | grep -v '^componentstatuses$'| xargs -n 1 kubectl get --all-namespaces --show-kind --ignore-not-found -l kustomize.component
NAME                                                                                                         CREATED AT
mutatingwebhookconfiguration.admissionregistration.k8s.io/admission-webhook-mutating-webhook-configuration   2019-07-24T13:52:49Z
NAME                                                                                       CREATED AT
customresourcedefinition.apiextensions.k8s.io/compositecontrollers.metacontroller.k8s.io   2019-07-24T13:52:01Z
customresourcedefinition.apiextensions.k8s.io/controllerrevisions.metacontroller.k8s.io    2019-07-24T13:52:01Z
customresourcedefinition.apiextensions.k8s.io/decoratorcontrollers.metacontroller.k8s.io   2019-07-24T13:52:01Z
customresourcedefinition.apiextensions.k8s.io/poddefaults.kubeflow.org                     2019-08-29T16:48:21Z
customresourcedefinition.apiextensions.k8s.io/profiles.kubeflow.org                        2019-08-29T16:54:24Z
NAME                                                                                            AGE
clusterrolebinding.rbac.authorization.k8s.io/admission-webhook-bootstrap-cluster-role-binding   3d16h
clusterrolebinding.rbac.authorization.k8s.io/admission-webhook-cluster-role-binding             3d16h
clusterrolebinding.rbac.authorization.k8s.io/argo                                               3d17h
clusterrolebinding.rbac.authorization.k8s.io/argo-ui                                            3d17h
clusterrolebinding.rbac.authorization.k8s.io/centraldashboard                                   3d17h
clusterrolebinding.rbac.authorization.k8s.io/meta-controller-cluster-role-binding               3d16h
clusterrolebinding.rbac.authorization.k8s.io/profiles-cluster-role-binding                      3d16h
clusterrolebinding.rbac.authorization.k8s.io/pytorch-operator                                   3d17h
clusterrolebinding.rbac.authorization.k8s.io/spartakus                                          3d16h
NAME                                                                             AGE
clusterrole.rbac.authorization.k8s.io/admission-webhook-bootstrap-cluster-role   39d
clusterrole.rbac.authorization.k8s.io/admission-webhook-cluster-role             39d
clusterrole.rbac.authorization.k8s.io/argo                                       95m
clusterrole.rbac.authorization.k8s.io/argo-ui                                    95m
clusterrole.rbac.authorization.k8s.io/centraldashboard                           95m
clusterrole.rbac.authorization.k8s.io/pytorch-operator                           92m
clusterrole.rbac.authorization.k8s.io/spartakus                                  39d
```

Unfortunately there are even more resources that have no tag at all but *look like* they are part of kubeflow like the clusterroles: `katib-controller, katib-ui, metacontroller, ml-pipeline-persistenceagent, ml-pipeline-viewer-controller-role, pipeline-runner`

And these clusterrolebindings: `katib-controller katib-ui metacontroller ml-pipeline-persistenceagent ml-pipeline-scheduledworkflow ml-pipeline-viewer-crd-role-binding pipeline-runner`

**Comment by discordianfish** [comment]
And more CRDs that aren't labeled either:
```
kubectl get crds|egrep 'kubeflow|dex'
authcodes.dex.coreos.com                      2019-08-29T16:46:42Z
authrequests.dex.coreos.com                   2019-08-29T16:46:42Z
connectors.dex.coreos.com                     2019-08-29T16:46:42Z
experiments.kubeflow.org                      2019-08-29T16:49:34Z
oauth2clients.dex.coreos.com                  2019-08-29T16:46:42Z
offlinesessionses.dex.coreos.com              2019-08-29T16:46:42Z
passwords.dex.coreos.com                      2019-08-29T16:46:42Z
pytorchjobs.kubeflow.org                      2019-08-29T16:51:08Z
refreshtokens.dex.coreos.com                  2019-08-29T16:46:42Z
scheduledworkflows.kubeflow.org               2019-08-29T16:54:09Z
signingkeies.dex.coreos.com                   2019-08-29T16:46:42Z
trials.kubeflow.org                           2019-08-29T16:49:35Z
viewers.kubeflow.org                          2019-08-29T16:53:53Z
```

So if anyone is in a similar situation like me and can't just recreate the k8s cluster on each update, this should clean up the remains (but it's not very safe, given there is no clear ownership label):
```
for labels in app.kubernetes.io/part-of=kubeflow kustomize.component; do
  kubectl api-resources --verbs=list -o name  | grep -v '^componentstatuses$' \
    | xargs -n 1 kubectl delete --all-namespaces --show-kind --ignore-not-found -l app.kubernetes.io/part-of=kubeflow
done

kubectl delete clusterroles        katib-controller katib-ui metacontroller ml-pipeline-persistenceagent ml-pipeline-viewer-controller-role pipeline-runner
kubectl delete clusterrolebindings katib-controller katib-ui metacontroller ml-pipeline-persistenceagent ml-pipeline-scheduledworkflow ml-pipeline-viewer-crd-role-binding pipeline-runner

kubectl get crd -o name| egrep 'kubeflow|dex'|xargs kubectl delete
```

**Comment by discordianfish** [comment]
More leftovers:
```
MutatingWebhookConfiguration admission-webhook-mutating-webhook-configuration
MutatingWebhookConfiguration experiment-mutating-webhook-config
MutatingWebhookConfiguration istio-sidecar-injector
MutatingWebhookConfiguration mutating-webhook-configuration
```

**Comment by yanniszark** [comment]
Since we are moving towards using the Application CRD and also the kfctl upgrade procedure depends on it, we could look into such an approach.
The restriction is that an Application CRD can only be consisted of namespaced resources.
In our case, we want both namespaced and cluster-wide resources (eg Profiles, Namespaces).

Relevant Issue: https://github.com/kubernetes-sigs/application/issues/111
/cc @kkasravi

**Comment by kkasravi** [comment]
@johnugeorge the instance labeling of applications is in the above PRs.
After this the logic in kustomize.deleteGlobalResources needs to be changed slightly - this PR hasn't been opened yet

**Comment by StianOvrevage** [comment]
I also notice that some (maybe all) of the istio resources have `heritage: Tiller` label. That is usually label used when `helm` installs stuff on a cluster. So I'm guessing the istio resources have been copied from a cluster where it was installed using helm.

These labels should be removed to avoid confusion for operators since istio is not managed by helm. Another option could be to actually use helm to deploy istio. That way helm could also be used to remove istio either as part of the clean-up or separately.

**Comment by kkasravi** [comment]
I don't believe we've done much to change the default istio install. @gabrielwen seems like we should cleanup misleading labels similar to how we removed ksonnet labels. Thoughts?

**Comment by StianOvrevage** [comment]
Helm v3 (now in beta) also does away with Tiller and does all of it's templating/generation client side. 

Maybe that would allow for using Helm for installing istio instead of the output of `helm template` stored side-by-side with the kubeflow installation files. Helm chart versions can be pinned if compatibility is a concern.

I would really like that approach because then I can manage istio similarly to other installations and not have to know two different istio installation patterns, especially with regards to how complex istio already is.

**Comment by jlewi** [comment]
Kubeflow doesn't use helm.

**Comment by Snapple49** [comment]
I had some major issues trying to reinstall kubeflow, since I'd accidentally introduced some components from the master manifests. Among others, kf-serving leaves behind some webhooks which prevented me from installing kubeflow again:
```
kubectl api-resources --verbs=list | grep hook
mutatingwebhookconfigurations                               admissionregistration.k8s.io   false        MutatingWebhookConfiguration
validatingwebhookconfigurations                             admissionregistration.k8s.io   false        ValidatingWebhookConfiguration

kubectl get mutatingwebhookconfigurations
NAME                                               CREATED AT
admission-webhook-mutating-webhook-configuration   2019-08-21T13:15:49Z
experiment-mutating-webhook-config                 2019-08-21T13:14:46Z
kfservice.serving.kubeflow.org                     2019-09-26T15:34:39Z
mutating-webhook-configuration                     2019-08-23T13:24:59Z

kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io 
NAME                                   CREATED AT
experiment-validating-webhook-config   2019-08-21T13:14:46Z
kfservice.serving.kubeflow.org         2019-09-14T20:34:59Z
studyjob-validating-webhook-config     2019-06-26T12:07:40Z
validating-webhook-configuration       2019-08-23T13:25:00Z

```

I'm not sure if all the hooks are from kubeflow, but at least the kfservice one was driving me insane. Basically I got this error when applying kfctl manifests, in case anyone else runs into this: 
```
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from katib-controller Error: Internal error occurred: failed calling webhook "kfservice.kfserving-webhook-server.deployment-mutator": Post https://kfserving-webhook-server-service.kubeflow.svc:443/mutate-deployments?timeout=30s: service "kfserving-webhook-server-service" not found
```

I didn't check their labels or so, so I couldn't verify if they were managed by kubeflow or similar, but it is indeed a major pain that non-namespaced resources are not cleaned up. I could imagine this problem is worse in on-prem clusters (as is my case) though, where it's harder to just tear down everything and try again with a fresh start. 

May I suggest a solution where you can provide an option for kfctl to label everything generated at install to be deleted when uninstalling? This way, it's easier to be aware that you'll remove everything related to kubeflow when uninstalling, so you don't accidentally remove for example your pre-existing istio.

**Comment by meandmymind** [comment]
For those looking for an easy hack, I guess following will help
`kubectl delete all -n istio-system --all`

**Comment by shaunc** [comment]
I haven't been able to install Kubeflow yet -- possibly related to this. Not only Istio is a problem. I'm now getting:
```
couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application katib-db
```
Maybe you should be prefixing namespace of other tools installed with `kubeflow-` (e.g. `kubeflow-istio-system`) and then they can be deleted to clean up. Optionally, then, you could offer the ability to share resources like istio on install. In this case, they wouldn't be deleted on cleanup.

In the meantime, ... how do I get rid of katib-db (etc.)? A full list rather than picking through the rubble would be great.

**Comment by srinjay-paul** [comment]
Issue still exists in kfctl v1.0-rc.1

**Comment by acesir** [comment]
It would be nice to have this issue resolved and kfctl delete actually cleanly removing all resources and CRD's. Does not seem possible in 0.7 or 1.0rc to cleanup kubeflow other than writing our own scripts to remove all resources.

**Comment by yanniszark** [comment]
This should be fixed in the latest kfctl.
We changed the delete algorithm.
/close

**Comment by crazy-canux** [comment]
this still exist on kfctl_1.0.2

**Comment by vigneshsolution** [comment]
@yanniszark  

Even we are facing the same with kfctl v1.0.2-0.

kfctl version
kfctl v1.0.2-0-ga476281


kubectl version --short
Client Version: v1.16.0
Server Version: v1.16.9

**Comment by vigneshsolution** [comment]
Guys its working fine with "kfctl v1.1.0-0"

Just now I tried.

**Comment by rganeshsharma** [comment]
Its still not removing CRD's and other resources such as CR, CRB, WebHooks and KfDef itself in kfctl v1.1.0-0
kubectl version --short                                                                                                                        
Client Version: v1.23.3
Server Version: v1.21.6+bb8d50a

**Comment by rganeshsharma** [comment]
@kkasravi Dear Ravi could you please direct me to how to use label for checking left over resources that KFDef created I am struggling to build Kubelfow cluster using ODH (https://opendatahub.io/docs/getting-started/quick-installation.html) . We are getting back the old profiles. As soon as new deployment is created old prfiles are picked up and this causes the issue and we are unable to see anything Central Dashboard UI. Please help
