### ISSUE TITLE
Kubeflow 1.2 AKS - No resource in `knative-serving` namespace

### ISSUE THREAD

**Issue by chiragjn** [kubeflow/kubeflow#5452]
/kind bug

**What steps did you take and what happened:**
I followed the kubeflow installation guide at https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/
I installed Istio 1.6.13 and applied the operator config https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-linux as linked in the first document

Only thing I changed is `CONFIG_URI` from
```
https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_azure.v1.1.0.yaml
```
to

```
https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_azure.v1.2.0.yaml
```
At this point, I am able to work with kubeflow dashboard and pipelines etc

I added gpu node pool, attached acr via service account, added nvidia plugin daemonset
After this I deployed my kfserving app in kubeflow namespace

```
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: myapp
  namespace: kubeflow
spec:
  default:
    predictor:
      serviceAccountName: azurecrcreds
      custom:
        name: myapp
        container:
          name: myapp
          image: kubeflowmltest.azurecr.io/myapp:0.2
          resources:
            limits:
              cpu: "1"
              memory: 2G
              nvidia.com/gpu: "1"
            requests:
              cpu: "1"
              memory: 2G
              nvidia.com/gpu: "1"
```

The pods and revision all come up fine

```
kubectl get pods -n kubeflow | grep myapp
```

```
myapp-predictor-default-x7cxs-deployment-85d6bdf8fc-svq57   2/2     Running   0          7h43m
```
But the service does not become ready

```
kubectl describe inferenceservice myapp  -n kubeflow
```

```
Name:         myapp
Namespace:    kubeflow
Labels:       <none>
Annotations:  <none>
API Version:  serving.kubeflow.org/v1alpha2
Kind:         InferenceService
Metadata:
  Creation Timestamp:  2020-12-10T04:40:08Z
  Generation:          1
  Resource Version:    15296861
  Self Link:           /apis/serving.kubeflow.org/v1alpha2/namespaces/kubeflow/inferenceservices/myapp
  UID:                 3706c915-055b-4459-9a48-8acc2904c70c
Spec:
  Default:
    Predictor:
      Custom:
        Container:
          Image:  kubeflowmltest.azurecr.io/myapp:0.2
          Name:   myapp
          Resources:
            Limits:
              Cpu:             1
              Memory:          2G
              nvidia.com/gpu:  1
            Requests:
              Cpu:             1
              Memory:          2G
              nvidia.com/gpu:  1
        Name:                  myapp
      Service Account Name:    azurecrcreds
Status:
  Canary:
  Conditions:
    Last Transition Time:  2020-12-10T04:40:18Z
    Message:               Ingress reconciliation failed
    Reason:                ReconcileIngressFailed
    Status:                Unknown
    Type:                  DefaultPredictorReady
    Last Transition Time:  2020-12-10T04:40:08Z
    Message:               Failed to reconcile predictor
    Reason:                PredictorHostnameUnknown
    Status:                False
    Type:                  Ready
    Last Transition Time:  2020-12-10T04:40:08Z
    Message:               Failed to reconcile predictor
    Reason:                PredictorHostnameUnknown
    Status:                False
    Type:                  RoutesReady
  Default:
    Predictor:
      Name:  myapp-predictor-default-x7cxs
Events:      <none>
```

Hence, I am unable to curl it via ingress load balancer's external IP

On browsing other issues I noticed that
1. My `istio-system` namespace is missing pilot pods. Are those needed? where I can find the proper istio configuration

```
kubectl get pods -n istio-system
```

```
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-7f5c797b55-lgdpg                1/1     Running   0          18h
istio-ingressgateway-5d78f74886-zpw7f   1/1     Running   0          18h
istio-tracing-57d7cfd779-xnpt8          1/1     Running   0          18h
istiod-58f84ffddc-9wmmm                 1/1     Running   0          18h
kiali-7c974669b4-jrn87                  1/1     Running   0          18h
prometheus-6946fd87b4-sg8gb             2/2     Running   1          18h
```

2. Similar to https://github.com/kubeflow/gcp-blueprints/issues/74 there are no resources in my `knative-serving` namespace

```
kubectl get all -n knative-serving
```

```
No resources found in knative-serving namespace.
```

3.  I did the gateway edits mentioned in https://github.com/kubeflow/kfserving/issues/928#issuecomment-656147750 but much like 2, I noticed that `config-istio` was also missing.

**What did you expect to happen:**

my kfserving app to come up correctly and be available via istio ingress load balancer

**Anything else you would like to add:**
N/A

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): kfctl v1.2.0-0-gbc038f9
- Kubernetes platform: (e.g. `minikube`): AKS
- Kubernetes version: (use `kubectl version`):
```
Client Version: v1.19.4
Server Version: v1.17.13
```
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04.6 LTS (Xenial Xerus)

Please feel to ask for any more information/logs. I don't have a lot of knowledge on how to debug this.
Can I run some sort of tests to check if my kubeflow system is setup as intended ?

**Comment by chiragjn** [comment]
Update:
As suspected, all `knative-serving` resources are being installed in `kubeflow` namespace causing failures in gateways.
I removed all `config-istio` configmaps from my `knative-serving` namespace

And then edited the `config-istio` under the `kubeflow` namespace to use the correct namespaces in gateways
```
gateway.knative-serving.knative-ingress-gateway: "istio-ingressgateway.istio-system.svc.cluster.local"
local-gateway.knative-serving.cluster-local-gateway: "cluster-local-gateway.istio-system.svc.cluster.local"
```
should be
```
gateway.kubeflow.kubeflow-gateway: istio-ingressgateway.istio-system.svc.cluster.local
local-gateway.kubeflow.cluster-local-gateway: cluster-local-gateway.istio-system.svc.cluster.local
```

And boom inferenceservice becomes ready and I can curl it via the external load balancer!
```
curl -X POST -v -H "Host: myapp-predictor-default.kubeflow.example.com" http://.../v1/models/myapp:predict -d '{"instances": [{"text": "test"}]}' -H 'Content-Type: application/json'
```

only one minor complain would be that
```
Host: myapp.kubeflow.example.com
```
results in 503 and does not work as documented in kfserving examples

**Comment by berndverst** [comment]
@chiragjn the CONFIG URI was a template variable that somehow wasn't updated when the 1.2 version of the docs was created. I just made a PR to fix that and a few other little things.

Now you know the secret that we usually deploy our trained ML models on Azure Machine Learning Service :)

I fixed the issue in the Azure config files. Once the following change is merged the v1.2 config files will correctly install KFServing and Knative going forward. Make sure to grab the latest `kfctl_azure.v1.2.0.yaml` at that time.
https://github.com/kubeflow/manifests/pull/1698

**Comment by fatimaafridi** [comment]
> Update:
> As suspected, all `knative-serving` resources are being installed in `kubeflow` namespace causing failures in gateways.
> I removed all `config-istio` configmaps from my `knative-serving` namespace
> 
> And then edited the `config-istio` under the `kubeflow` namespace to use the correct namespaces in gateways
> 
> ```
> gateway.knative-serving.knative-ingress-gateway: "istio-ingressgateway.istio-system.svc.cluster.local"
> local-gateway.knative-serving.cluster-local-gateway: "cluster-local-gateway.istio-system.svc.cluster.local"
> ```
> 
> should be
> 
> ```
> gateway.kubeflow.kubeflow-gateway: istio-ingressgateway.istio-system.svc.cluster.local
> local-gateway.kubeflow.cluster-local-gateway: cluster-local-gateway.istio-system.svc.cluster.local
> ```
> 
> And boom inferenceservice becomes ready and I can curl it via the external load balancer!
> 
> ```
> curl -X POST -v -H "Host: myapp-predictor-default.kubeflow.example.com" http://.../v1/models/myapp:predict -d '{"instances": [{"text": "test"}]}' -H 'Content-Type: application/json'
> ```
> 
> only one minor complain would be that
> 
> ```
> Host: myapp.kubeflow.example.com
> ```
> 
> results in 503 and does not work as documented in kfserving examples

@berndverst  kubeflow v1.2 AKS config file lacks cluster local gateway installation:

  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/kubernetes/application/cluster-local-gateway-1-3-1
    name: cluster-local-gateway 

one of a susceptible cause to "503, service unavailable" issue with KFServing custom sample run

**Comment by berndverst** [comment]
@fatimaafridi I don't know enough about how kfserving or cluster-local-gateway work.

The cluster local gateway is currently only provided with the Azure Active Directory multi-tenancy variant of the Kubeflow deploy configs. That however uses Istio 1-3-1.

After doing some spelunking just now it seems that there is a cluster local gateway that will work with Istio 1.6.X -- but that is located here:
https://github.com/kubeflow/manifests/tree/master/istio/cluster-local-gateway

Here's something you can try -- download the `kfctl_azurev1.2.0.yaml` and add the following:

```yaml
  - kustomizeConfig: 
      repoRef:
        name: manifests
        path: stacks/kubernetes/application/cluster-local-gateway
```

Or just grab this file from my branch:
https://github.com/berndverst/manifests/blob/v1.2-branch/kfdef/kfctl_azure.v1.2.0.yaml

Then use `kfctl` to deploy this modified config file. It should install a cluster local gateway that is compatible with Istio 1.6.X from what I've read now.

Would be amazing if someone could confirm that this fixes the issue and doesn't introduce new problems. Again, don't know much about KFServing, Knative and the cluster local gateway.

**Comment by fatimaafridi** [comment]
@berndverst verified this fix. It adds a cluster local gateway but doesn't resolve the service unavailability response issue.

**Comment by fatimaafridi** [comment]
@berndverst  Resolved the service unavailability issue. Despite the fact that a 1.6.x istio version is installed prior to deployment, I also added istio-stack installation to my config file for kubeflow deployment. One thing to notice is that the stack is 1-3 based but it seems like istio-stack-1-3 adds some crds and other requirements deemed necessary for KFServing.(possibly)

Here are the two changes done to the kfctl_azurev1.2.0.yaml:

`  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/kubernetes/application/cluster-local-gateway
    name: cluster-local-gateway
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/azure/application/istio-1-3-1-stack
    name: istio-stack`

When the modified config file is deployed and a request to inferenceservice is made, it gives proper response.

**Comment by berndverst** [comment]
@fatimaafridi seems likely!

What's a simple way for me to reproduce the original issue? What URL should I access, or what should I configure first?

I think adding the Istio 1.6(?) CRDs from here should also do the trick.

I refactored things a bit. Here is the updated deployment config from my branch:
https://github.com/berndverst/manifests/blob/v1.2-branch/kfdef/kfctl_azure.v1.2.0.yaml

The key difference is actually here:
https://github.com/berndverst/manifests/commit/ecfaddd1d8ab843ae8a7b6d8cbe389bad9f14b97

If you want to try that (though you already have a working environment so I understand if you do not) you'll need to change the repo in the above `kfctl_azure.v1.2.0.yaml` to `berndverst/manifests` instead. The pinned commit ID is correct however.

**Comment by fatimaafridi** [comment]
@berndverst If you have a running instance of kubeflow v1.2, just follow the straightforward steps here (clone the kfserving repo beforehand and navigate to the hello-word sample directory) :
https://github.com/kubeflow/kfserving/tree/release-0.4/docs/samples/custom/hello-world

You need no additional configuration to test kfserving. If you are able to access the URL successfully then the manifest fixes are good to go!

**Comment by danishsamad** [comment]
@berndverst @fatimaafridi I ran into the same issue and was able to resolve the issue by making the following changes

1. Update kfctl_azure.v.1.2.0.yaml by adding cluster-local-gateway 

  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/kubernetes/application/cluster-local-gateway
    name: cluster-local-gateway

2. Edit cluster-local-gateway deployment
kubectl edit deployment -n istio-system cluster-local-gateway

3. Modify discoveryAddress arg to refer to istiod instead of istio pilot
 - --discoveryAddress
 - istiod.istio-system:15010

4. Add a new environment variable
 - name: ISTIO_META_CLUSTER_ID
    value: Kubernetes

I ran the [tensorflow sample](https://github.com/kubeflow/kfserving/tree/v0.4.1/docs/samples/tensorflow) successfully to verify 
installation

Can these changes be verified and  incorporated in the 1.2 manifest? 

Note:
I tried the changes in the https://github.com/berndverst/manifests/blob/v1.2-branch/kfdef/kfctl_azure.v1.2.0.yaml branch but this installed cluster-local-gateway in the kubeflow namespace so I left it there

**Comment by DavidSpek** [comment]
Can somebody confirm this issue has been solved so that it can be closed? It seems this is an Istio related problem, which should be solved with the upcoming Kubeflow 1.3 release that will properly support Istio 1.6+ and include Istio 1.9 by default.

**Comment by danishsamad** [comment]
> ease that will properly support Istio 1.6+ and include Istio 1.9 by default.

It seems to be more related to missing / misconfigurations that were not corrected to comply with istio 1.6. You can check my suggested changes to verify if it works for you and incorporate in the 1.2 branch
